# Generated by Django 4.2.7 on 2023-11-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawtransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transid', models.TextField(db_index=True, max_length=20)),
                ('description', models.TextField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=20)),
                ('symbol', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=20)),
            ],
        ),
    ]
