# Generated by Django 4.2.7 on 2023-11-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_rawtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawcsv',
            name='type',
            field=models.CharField(choices=[('SC', 'Schwab'), ('TD', 'TD Ameritrade')], default='TD', max_length=2),
        ),
    ]
