# Generated by Django 4.2.7 on 2023-11-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_rawcsv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawcsv',
            name='type',
            field=models.CharField(choices=[('SC', 'Schwab'), ('TD', 'TD Ameritrade'), ('UN', 'Unknown')], default='UN', max_length=2),
        ),
    ]
