# Generated by Django 4.2.7 on 2023-11-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_alter_rawcsv_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransactions',
            name='transid',
            field=models.TextField(db_index=True, max_length=20, unique=True),
        ),
    ]
