# Generated by Django 4.2.7 on 2023-11-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_alter_rawtransactions_transid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransactions',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='symbol',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
