# Generated by Django 4.2.7 on 2023-11-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_alter_rawtransactions_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtransactions',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='symbol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawtransactions',
            name='transid',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
