# Generated by Django 4.2.7 on 2023-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_alter_rawtransactions_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtransactions',
            name='rawline',
            field=models.TextField(default=''),
        ),
    ]
